### ISSUE TITLE
please introduce  a wait time after getting a 4XX back from the token creation

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/tokens#10]
Without the delay, the token creation endpoint would be flooded with endless requests which just result in another 4XX. The cause for 4XX status codes is on the client side, i.e. wrong or outdated credentials which most likely do not get fixed until the next call a few milliseconds later

**Comment by lukasniemeier-zalando** [comment]
+1

**Comment by jbellmann** [comment]
Lets first try out to only increase the period between refresh from 1 second to every 5 seconds. Maybe this is enough to avoid 'flooding' the endpoint.
