### ISSUE TITLE
Missing connection timeout

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-stups/tokens#12]
`AccessTokenRefresher` does not set any timeouts on its [call to the token endpoint](https://github.com/zalando-stups/tokens/blob/master/src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java#L210). This could lead to a call blocking all later refresh attempts.

* Set sane defaults for connect and read timeouts
* Allow those to be customized
* Maybe wrap the whole HTTP call in a timed async execution

**Comment by hjacobs** [comment]
True, looks like a timeout is needed here :+1:

**Comment by jbellmann** [comment]
@hjacobs , @lukasniemeier-zalando 

please have a look at the PR #15 and provide useful values for timeouts please.

**Comment by lukasniemeier-zalando** [comment]
Looks like this is solved with #14 :+1:
