### ISSUE TITLE
Low test coverage

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/tokens#23]
To be honest I just looked at the badge (maybe it is inaccurate, we have that problem with our Clojure stuff) but imo this library is quite essential and should therefore have more tests.

**Comment by hjacobs** [comment]
:+1: yes, the badge was wrong (pointed to wrong branch) --- but it's still only 26% line coverage

**Comment by hjacobs** [comment]
I think we need to fix #22 first :smile:
