### ISSUE TITLE
Implement background checks for token validity

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/tokens#36]
If a token somehow gets invalid before its expected end of life, the tokens library doesn't recognize it and will keep the invalid token until its expired. The following TODO should be implemented:
https://github.com/zalando-stups/tokens/blob/master/src/main/java/org/zalando/stups/tokens/AccessTokenRefresher.java#L110

Regularly check in the background thread if the token is still valid.

**Comment by Jan-M** [comment]
This is in general a good idea, but most issues we ran into was basically regions out of sync and this would not be found here as in local region token was valid.
