### ISSUE TITLE
Set User-Agent to identify this library

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/tokens#37]
When doing HTTP requests from within this library, the user agent should be set to `org.zalando.stups.tokens (0.9.15)` in order to identify requests coming from the standard library and which version is used.

**Comment by jbellmann** [comment]
#39 should solve this

**Comment by hjacobs** [comment]
I would strongly suggest to use the "standard" User-Agent format (curl and Python use it), i.e. "/":

Examples:

* User-Agent: curl/7.43.0
* User-Agent: python-requests/2.9.1
