### ISSUE TITLE
Allow testing OAuth2 locally by providing access tokens via environment variables

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/tokens#4]
The "tokens" library should support passing in personal access tokens (generated by "zign") in order to do local testing.

**Comment by jbellmann** [comment]
Pullrequest merged and new version of 'tokens' released (0.7.0). Should be available in Maven-Central now.

**Comment by hjacobs** [comment]
TODO: add documentation how to test locally using the new OAUTH2_ACCESS_TOKENS environment variable

**Comment by hjacobs** [comment]
This is broken right now: it uses System.getProperty instead of getEnv..

**Comment by lukasniemeier** [comment]
@hjacobs works in 0.9.0

**Comment by hjacobs** [comment]
@lukasniemeier great, thanks :+1:
