### ISSUE TITLE
httpclient is in "provided" scope in pom.xml

### ISSUE THREAD

**Issue by ovolynets** [zalando-stups/tokens#44]
For a plain Scala-Play application adding just the ```tokens``` library to the sbt dependencies is not sufficient and has to be accompanied with ```org.apache.httpcomponents.httpclient``` library. Was there a reason to have ```httpclient``` in ```provided``` scope? It would make sense to add a note for scala users to add the ```httpclient``` dependency if needed.

**Comment by harti2006** [comment]
Hi, the "provided" scope is intentional. It was introduced with a Pull Request that allows to replace httpclient with a different implementation. However you a right when saying that this should be documented.

**Comment by ovolynets** [comment]
Great to see the updated documentation, thanks
