### ISSUE TITLE
Proposed move to main Zalando org

### ISSUE THREAD

**Issue by LappleApple** [zalando-stups/tokens#49]
If I'm not mistaken this is useful out-of-the-box and not dependent on STUPS. We could shift to main org and try to promote it more.

**Comment by prayerslayer** [comment]
Hi, this depends on valid credentials (that will be accepted by an OAuth provider such as zalando/planb-provider) being available on the local filesystem, which in the STUPS infrastructure is done by mint-worker and berry. I haven't seen this when working with, say, Github or Twitter APIs, so I'd say it's STUPS dependent.

**Comment by LappleApple** [comment]
Ah, OK. I was actually pointed to this project by an engineer who thought it was out-of-the-box useful; seems there could be a misunderstanding.

**Comment by ePaul** [comment]
@prayerslayer Maybe this dependency could be pointed out in the README?
